name: Azure PowerShell Automation CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Az module
        shell: pwsh
        run: |
          Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber

      - name: Run PowerShell VM script
        shell: pwsh
        run: |
          ./CreateWinVm.ps1 *>output.txt
